package com.machiav3lli.fdroid.ui.compose.theme

import androidx.compose.ui.graphics.Color

val PitchBlack = Color(0xFF000000)
val GreyDark = Color(0xFF2C2C2C)

val Orange = Color(0xFFFF9138)
val LightGreen = Color(0xFFAEC300)

// Light Theme
val md_theme_light_primary = Color(0xFF006E24)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6DFF7F)
val md_theme_light_onPrimaryContainer = Color(0xFF002106)
val md_theme_light_secondary = Color(0xFF1760A5)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD3E3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001C39)
val md_theme_light_tertiary = Color(0xFF006A62)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF72F7E9)
val md_theme_light_onTertiaryContainer = Color(0xFF00201D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF5FFF3)
val md_theme_light_onBackground = Color(0xFF00210E)
val md_theme_light_surface = Color(0xFFF5FFF3)
val md_theme_light_onSurface = Color(0xFF00210E)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFC2FFD0)
val md_theme_light_inverseSurface = Color(0xFF00391C)
val md_theme_light_inversePrimary = Color(0xFF2EE45B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006E24)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme
val md_theme_dark_primary = Color(0xFF2EE45B)
val md_theme_dark_onPrimary = Color(0xFF00390E)
val md_theme_dark_primaryContainer = Color(0xFF005319)
val md_theme_dark_onPrimaryContainer = Color(0xFF6DFF7F)
val md_theme_dark_secondary = Color(0xFFA3C9FF)
val md_theme_dark_onSecondary = Color(0xFF00315C)
val md_theme_dark_secondaryContainer = Color(0xFF004882)
val md_theme_dark_onSecondaryContainer = Color(0xFFD3E3FF)
val md_theme_dark_tertiary = Color(0xFF51DBCD)
val md_theme_dark_onTertiary = Color(0xFF003733)
val md_theme_dark_tertiaryContainer = Color(0xFF00504A)
val md_theme_dark_onTertiaryContainer = Color(0xFF72F7E9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF00210E)
val md_theme_dark_onBackground = Color(0xFF99F7B5)
val md_theme_dark_surface = Color(0xFF00210E)
val md_theme_dark_onSurface = Color(0xFF99F7B5)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF00210E)
val md_theme_dark_inverseSurface = Color(0xFF99F7B5)
val md_theme_dark_inversePrimary = Color(0xFF006E24)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF2EE45B)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF22DD55)