package com.machiav3lli.fdroid.ui.compose.theme

import androidx.compose.ui.graphics.Color

val PitchBlack = Color(0xFF000000)
val GreyDark = Color(0xFF2C2C2C)

val Orange = Color(0xFFFF9138)
val LightGreen = Color(0xFFAEC300)

// Light Theme
val md_theme_light_primary = Color(0xFF006D3E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF96F7B8)
val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
val md_theme_light_secondary = Color(0xFF4F6354)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E8D5)
val md_theme_light_onSecondaryContainer = Color(0xFF0C1F13)
val md_theme_light_tertiary = Color(0xFFAA4444)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDCC)
val md_theme_light_onTertiaryContainer = Color(0xFF551111)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFE8F5E9)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717971)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF7ADA9D)
val md_theme_light_shadow = Color(0xFF000000)

// Dark Theme
val md_theme_dark_primary = Color(0xFF7ADA9D)
val md_theme_dark_onPrimary = Color(0xFF00391E)
val md_theme_dark_primaryContainer = Color(0xFF00522D)
val md_theme_dark_onPrimaryContainer = Color(0xFF96F7B8)
val md_theme_dark_secondary = Color(0xFFB6CCB9)
val md_theme_dark_onSecondary = Color(0xFF213527)
val md_theme_dark_secondaryContainer = Color(0xFF384B3D)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E8D5)
val md_theme_dark_tertiary = Color(0xFFFFCCCC)
val md_theme_dark_onTertiary = Color(0xFF551111)
val md_theme_dark_tertiaryContainer = Color(0xFFAA4444)
val md_theme_dark_onTertiaryContainer = Color(0xFFEEDDDD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D3E)
val md_theme_dark_shadow = Color(0xFF000000)


val seed = Color(0xFF006D3E)