package com.saggitt.omega

// DESKTOP PREFS
const val PREFS_DESKTOP_ICON_SCALE = "pref_home_icon_scale"
const val PREFS_DESKTOP_HIDE_LABEL = "pref_hide_app_label"
const val PREFS_DESKTOP_ICON_LABEL_TWOLINES = "pref_icon_labels_two_lines"
const val PREFS_DESKTOP_ICON_TEXT_SCALE = "pref_icon_text_scale"
const val PREFS_DESKTOP_POPUP_MENU = "pref_desktopUsePopupMenuView"
const val PREFS_DESKTOP_LOCK = "pref_lockDesktop"
const val PREFS_WIDGETS_FULL_WIDTH = "pref_full_width_widgets"
const val PREFS_EMPTY_SCREENS = "pref_keepEmptyScreens"
const val PREFS_FOLDER_RADIUS = "pref_folder_radius"
const val PREFS_FOLDER_COLUMNS = "pref_folder_columns"
const val PREFS_FOLDER_ROWS = "pref_folder_rows"
const val PREFS_FOLDER_BACKGROUND = "pref_folder_background"
const val PREFS_FOLDER_BACKGROUND_CUSTOM = "pref_custom_folder_background"
const val PREFS_STATUSBAR_HIDE = "pref_hideStatusBar"
const val PREFS_DASH_LINESIZE = "pref_dash_linesize"
const val PREFS_DASH_PROVIDERS = "pref_dash_providers"

// DOCK PREFS
const val PREFS_DOCK_HIDE = "pref_hideHotseat"
const val PREFS_DOCK_ICON_SCALE = "pref_hotseat_icon_scale"
const val PREFS_DOCK_SCALE = "pref_dockScale"
const val PREFS_DOCK_BACKGROUND = "pref_dockBackground"
const val PREFS_DOCK_BACKGROUND_COLOR = "pref_dock_background_color"
const val PREFS_DOCK_OPACITY = "pref_dockOpacity"

// DRAWER PREFS
const val PREFS_SORT = "pref_sortMode"
const val PREFS_PROTECTED_APPS = "pref_protected_apps"
const val PREFS_TRUST_APPS = "pref_trust_apps"
const val PREFS_HIDDEN_SET = "hidden_app_set"
const val PREFS_HIDDEN_PREDICTION_SET = "pref_hidden_prediction_set"
const val PREFS_PROTECTED_SET = "protected_app_set"
const val PREFS_DRAWER_ICON_SCALE = "pref_allapps_icon_scale"
const val PREFS_DRAWER_ICON_TEXT_SCALE = "pref_allapps_icon_text_scale"
const val PREFS_DRAWER_HIDE_LABEL = "pref_hide_allapps_app_label"
const val PREFS_DRAWER_ICON_LABEL_TWOLINES = "pref_apps_icon_labels_two_lines"
const val PREFS_DRAWER_HEIGHT_MULTIPLIER = "pref_allAppsCellHeightMultiplier"
const val PREFS_WORK_PROFILE_SEPARATED = "pref_separateWorkApps"
const val PREFS_KEEP_SCROLL_STATE = "pref_keep_scroll_state"

// THEME PREFS
const val PREFS_THEME = "pref_launcherTheme"
const val PREFS_ACCENT = "pref_accent_color"
const val PREFS_BLUR = "pref_enableBlur"
const val PREFS_BLUR_RADIUS = "pref_blurRadius"
const val PREFS_WINDOWCORNER = "pref_customWindowCorner"
const val PREFS_WINDOWCORNER_RADIUS = "pref_customWindowCornerRadius"
const val PREFS_ICON_PACK = "pref_icon_pack_package"
const val PREFS_ICON_SHAPE = "pref_iconShape"
const val PREFS_COLORED_BACKGROUND = "pref_colored_background"
const val PREFS_WHITE_TREATMENT = "pref_white_only_treatment"
const val PREFS_LEGACY_TREATMENT = "pref_legacy_treatment"
const val PREFS_FORCE_ADAPTIVE = "pref_adaptive_icon_pack"
const val PREFS_FORCE_SHAPELESS = "pref_force_shape_less"

// SEARCH PREFS
const val PREFS_SEARCH_PROVIDER = "pref_global_search_provider"

// GESTURES PREFS
const val PREFS_NOTIFICATION_COUNT = "pref_notification_count"
const val PREFS_NOTIFICATION_BACKGROUND_CUSTOM = "pref_custom_background"
const val PREFS_NOTIFICATION_BACKGROUND = "pref_notification_background"
const val PREFS_NOTIFICATION_COUNT_FOLDER = "pref_folder_badge_count"
const val NOTIFICATION_BADGING = "notification_badging"
const val NOTIFICATION_DOTS_PREFERENCE_KEY = "pref_icon_badging"
const val PREFS_GESTURE_DOUBLE_TAP = "pref_gesture_double_tap"
const val PREFS_GESTURE_LONG_PRESS = "pref_gesture_long_press"
const val PREFS_GESTURE_HOME = "pref_gesture_press_home"
const val PREFS_GESTURE_BACK = "pref_gesture_press_back"
const val PREFS_GESTURE_SWIPE_DOWN = "pref_gesture_swipe_down"
const val PREFS_GESTURE_SWIPE_UP = "pref_gesture_swipe_up"
const val PREFS_GESTURE_SWIPE_UP_DOCK = "pref_gesture_dock_swipe_up"
const val PREFS_GESTURE_ASSISTANT = "pref_gesture_launch_assistant"

//SMARTSPACE PREFS
const val PREFS_SMARTSPACE_SHOW = "pref_show_smartspace"
const val PREFS_SMARTSPACE_ENABLE = "enable_smartspace"
const val PREFS_SMARTSPACE_DATE = "pref_smartspace_date"
const val PREFS_SMARTSPACE_TIME = "pref_smartspace_time"
const val PREFS_SMARTSPACE_TIME_ABOVE = "pref_smartspace_time_above"
const val PREF_PILL_QSB = "pref_use_pill_qsb"
const val PREFS_TIME_24H = "pref_smartspace_time_24_h"

// ADVANCED PREFS
const val PREFS_LANGUAGE = "pref_language"
const val PREFS_FIRST_RUN = "pref_first_run"
const val PREFS_RESTORE_SUCCESS = "pref_restore_success"
const val PREFS_RECENT_BACKUP = "pref_recent_backups"

// DEVELOPER PREFS
const val PREFS_DEV_PREFS_SHOW = "pref_showDevOptions"
const val PREFS_DESKTOP_MODE = "pref_desktop_mode"
const val PREFS_DESKTOP_MODE_SETTINGS = "pref_desktop_mode_settings"
const val PREFS_LOW_PREFORMANCE = "pref_lowPerformanceMode"
const val PREFS_DEBUG_MODE = "pref_showDebugInfo"
const val PREFS_KILL = "kill"

// EXTRA PREFS
const val PREFS_ROWS = "numRows"
const val PREFS_COLUMNS = "numColumns"
const val PREFS_FEED_PROVIDER = "pref_feedProvider"
const val PREFS_FEED_PROVIDER_ALLOW_ALL = "pref_feedProviderAllowAll"
const val PREFS_TORCH = "pref_torch"
const val PREFS_DESKTOP_POPUP_EDIT = "desktop_popup_edit"
const val PREFS_DESKTOP_POPUP_REMOVE = "desktop_popup_remove"
const val PREFS_DRAWER_POPUP_EDIT = "drawer_popup_edit"
const val PREFS_DRAWER_POPUP_UNINSTALL = "drawer_popup_uninstall"
const val PREFS_FOLDER_COVER_MODE = "pref_cover_mode"
const val PREFS_APP_SHOW_IN_TABS = "pref_show_in_tabs"
const val PREFS_APP_HIDE = "pref_app_hide"
const val PREFS_APP_ICON_MAP = "pref_appIconMap"
